/**
 * 단원별 추가 메타데이터 오버라이드.
 *
 * parse-curriculum 의 출력은 마스터 인덱스 표 정보만 담음 (status='planned').
 * 단원 작업이 시작되면 여기에 추가 메타를 박아 두면 자동 머지된다.
 *
 * 머지 규칙: lib/curriculum/index.ts 의 applyOverrides 가
 *   parse 출력 객체 + override = 최종 객체 로 spread 합성한다.
 *
 * 추가 항목 예:
 *   - status: 'draft' | 'reviewed' | 'published'
 *   - prerequisites
 *   - achievementStandards (NCIC 성취기준 코드)
 *   - componentName (인터랙티브 React 컴포넌트 export 명)
 *   - patternIds (02-component-catalog 의 1~20)
 */
import type { HighSchoolUnit, Unit } from '../types';

type Override = Partial<Omit<Unit, 'id'>> & Partial<Omit<HighSchoolUnit, 'id'>>;

export const UNIT_OVERRIDES: Record<string, Override> = {
  'M9-CR-03': {
    status: 'draft',
    prerequisites: ['M8-CR-04', 'M9-CR-01'],
    achievementStandards: ['[9수03-08]'],
    componentName: 'QuadraticFunctionExplorer',
    patternIds: [1],
  },
  'H5-HI-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6사07-01]', '[6사07-02]'],
    componentName: 'KoreanHistoryTimeline',
    patternIds: [7],
  },
  'M5-NA-04': {
    status: 'draft',
    prerequisites: ['M5-NA-03', 'M4-NA-03'],
    achievementStandards: ['[6수01-09]'],
    componentName: 'FractionAddSubExplorer',
    patternIds: [1, 12],
  },
  'E-GR-04': {
    status: 'draft',
    prerequisites: ['E-GR-03'],
    achievementStandards: [],
    componentName: 'TenseTimelineExplorer',
    patternIds: [7, 12],
  },
  'H8-SO-02': {
    status: 'draft',
    prerequisites: ['H8-SO-01'],
    achievementStandards: ['[9사(일사)05-01]'],
    componentName: 'SupplyDemandExplorer',
    patternIds: [1, 14],
  },
  'S7-MA-01': {
    status: 'draft',
    prerequisites: ['S3-MA-02'],
    achievementStandards: ['[9과02-01]'],
    componentName: 'ParticleStateSimulator',
    patternIds: [4],
  },
  'M3-NA-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수01-10]'],
    componentName: 'FractionMeaningExplorer',
    patternIds: [12],
  },
  'M7-NA-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[9수01-01]'],
    componentName: 'PrimeFactorTree',
    patternIds: [13],
  },
  'M7-NA-02': {
    status: 'draft',
    prerequisites: ['M7-NA-01'],
    achievementStandards: ['[9수01-02]'],
    componentName: 'IntegerNumberLine',
    patternIds: [1],
  },
  'K-RD-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TextStructureTree',
    patternIds: [13],
  },
  'E-VOC-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PhonicsExplorer',
    patternIds: [11],
  },
  'M3-NA-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수01-02]'],
    componentName: 'PlaceValueBlocks',
    patternIds: [12],
  },
  'M6-NA-01': {
    status: 'draft',
    prerequisites: ['M5-NA-04'],
    achievementStandards: ['[6수01-10]'],
    componentName: 'FractionDivisionExplorer',
    patternIds: [12],
  },
  'M6-CR-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6수02-08]'],
    componentName: 'RatioExplorer',
    patternIds: [14],
  },
  'M6-CR-02': {
    status: 'draft',
    prerequisites: ['M6-CR-01'],
    achievementStandards: ['[6수02-09]'],
    componentName: 'ProportionBalance',
    patternIds: [6, 14],
  },
  'S5-MA-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과11-01]'],
    componentName: 'PHIndicator',
    patternIds: [1],
  },
  'S5-LI-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과10-01]'],
    componentName: 'BiologyClassificationTree',
    patternIds: [13],
  },
  'M4-NA-01': {
    status: 'draft',
    prerequisites: ['M3-NA-01'],
    achievementStandards: ['[4수01-01]'],
    componentName: 'BigNumberPlaceValue',
    patternIds: [12],
  },
  'M4-NA-04': {
    status: 'draft',
    prerequisites: ['M3-NA-01'],
    achievementStandards: ['[4수01-15]'],
    componentName: 'DecimalPlaceColumns',
    patternIds: [12],
  },
  'M4-CR-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수02-01]'],
    componentName: 'SequencePatternDetector',
    patternIds: [14],
  },
  'M5-CR-01': {
    status: 'draft',
    prerequisites: ['M4-CR-01'],
    achievementStandards: ['[6수02-01]'],
    componentName: 'FunctionBoxExplorer',
    patternIds: [1, 14],
  },
  'S5-LI-02': {
    status: 'draft',
    prerequisites: ['S5-LI-01'],
    achievementStandards: ['[6과13-01]'],
    componentName: 'FoodWebExplorer',
    patternIds: [13],
  },
  'S5-EU-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과14-01]'],
    componentName: 'SolarSystemExplorer',
    patternIds: [17],
  },
  'H4-GE-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4사02-01]'],
    componentName: 'KoreaRegionExplorer',
    patternIds: [8],
  },
  'H6-HI-01': {
    status: 'draft',
    prerequisites: ['H5-HI-01'],
    achievementStandards: ['[6사07-04]'],
    componentName: 'KoreanModernHistoryTimeline',
    patternIds: [7],
  },
  'M5-DP-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6수04-01]'],
    componentName: 'AverageSimulator',
    patternIds: [10, 14],
  },
  'M6-DP-01': {
    status: 'draft',
    prerequisites: ['M5-DP-01', 'M6-CR-01'],
    achievementStandards: ['[6수04-04]'],
    componentName: 'PercentChart',
    patternIds: [14],
  },
  'M5-GM-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6수03-04]'],
    componentName: 'PolygonAreaExplorer',
    patternIds: [6],
  },
  'S6-LI-01': {
    status: 'draft',
    prerequisites: ['S5-LI-01'],
    achievementStandards: ['[6과12-01]'],
    componentName: 'HumanBodySystems',
    patternIds: [8, 13],
  },
  'S6-LI-02': {
    status: 'draft',
    prerequisites: ['S6-LI-01'],
    achievementStandards: ['[6과12-02]'],
    componentName: 'PhotosynthesisExplorer',
    patternIds: [1, 4],
  },
  'S6-EU-02': {
    status: 'draft',
    prerequisites: ['S5-EU-01'],
    achievementStandards: ['[6과14-03]'],
    componentName: 'SeasonsExplorer',
    patternIds: [4, 17],
  },
  'M5-NA-05': {
    status: 'draft',
    prerequisites: ['M5-NA-04'],
    achievementStandards: ['[6수01-08]'],
    componentName: 'FractionMultiplicationExplorer',
    patternIds: [1, 12],
  },
  'K-LT-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PoemStructureExplorer',
    patternIds: [13],
  },
  'K-LT-02': {
    status: 'draft',
    prerequisites: ['K-LT-01'],
    achievementStandards: [],
    componentName: 'PlotDiagramExplorer',
    patternIds: [7, 14],
  },
  'M3-NA-02': {
    status: 'draft',
    prerequisites: ['M3-NA-01'],
    achievementStandards: ['[4수01-04]'],
    componentName: 'AreaModelMultiplication',
    patternIds: [12],
  },
  'M4-NA-02': {
    status: 'draft',
    prerequisites: ['M3-NA-02'],
    achievementStandards: ['[4수01-05]'],
    componentName: 'StandardMultiplicationAlgorithm',
    patternIds: [7],
  },
  'M4-NA-03': {
    status: 'draft',
    prerequisites: ['M3-NA-04'],
    achievementStandards: ['[4수01-13]'],
    componentName: 'FractionAddSubExplorer',
    patternIds: [12],
  },
  'M5-NA-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6수01-01]'],
    componentName: 'OrderOfOperationsTrainer',
    patternIds: [1, 7],
  },
  'S3-LI-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4과05-01]'],
    componentName: 'AnimalHabitatExplorer',
    patternIds: [13],
  },
  'S5-MA-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과07-01]'],
    componentName: 'SolutionParticleSimulator',
    patternIds: [4],
  },
  'M3-NA-03': {
    status: 'draft',
    prerequisites: ['M3-NA-02'],
    achievementStandards: ['[4수01-07]'],
    componentName: 'DivisionRemainderExplorer',
    patternIds: [12],
  },
  'M3-NA-05': {
    status: 'draft',
    prerequisites: ['M3-NA-04'],
    achievementStandards: ['[4수01-14]'],
    componentName: 'DecimalPlaceColumns',
    patternIds: [12],
  },
  'M5-NA-02': {
    status: 'draft',
    prerequisites: ['M3-NA-03'],
    achievementStandards: ['[6수01-02]'],
    componentName: 'PrimeFactorTree',
    patternIds: [13],
  },
  'M5-NA-03': {
    status: 'draft',
    prerequisites: ['M5-NA-02'],
    achievementStandards: ['[6수01-04]'],
    componentName: 'FractionAddSubExplorer',
    patternIds: [12],
  },
  'E-LIS-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PhonicsExplorer',
    patternIds: [11],
  },
  'E-SPK-01': {
    status: 'draft',
    prerequisites: ['E-LIS-01'],
    achievementStandards: [],
    componentName: 'PhonicsExplorer',
    patternIds: [11],
  },
  'K-GR-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HangulSystemExplorer',
    patternIds: [13],
  },
  'K-RD-02': {
    status: 'draft',
    prerequisites: ['K-RD-01'],
    achievementStandards: [],
    componentName: 'FactOpinionSorter',
    patternIds: [11],
  },
  'E-REA-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TextStructureTree',
    patternIds: [13],
  },
  'E-WRI-01': {
    status: 'draft',
    prerequisites: ['E-REA-01'],
    achievementStandards: [],
    componentName: 'TextStructureTree',
    patternIds: [13],
  },
  'H6-HI-02': {
    status: 'draft',
    prerequisites: ['H6-HI-01'],
    achievementStandards: ['[6사07-05]'],
    componentName: 'KoreanModernHistoryTimeline',
    patternIds: [7],
  },
  'E-VOC-02': {
    status: 'draft',
    prerequisites: ['E-VOC-01'],
    achievementStandards: [],
    componentName: 'PhonicsExplorer',
    patternIds: [11],
  },
  'H7-GE-01': {
    status: 'draft',
    prerequisites: ['H4-GE-01'],
    achievementStandards: ['[9사(지리)01-01]'],
    componentName: 'WorldContinentExplorer',
    patternIds: [8],
  },
  'E-VOC-03': {
    status: 'draft',
    prerequisites: ['E-VOC-02'],
    achievementStandards: [],
    componentName: 'SynonymAntonymMatcher',
    patternIds: [11],
  },
  'E-VOC-04': {
    status: 'draft',
    prerequisites: ['E-VOC-02'],
    achievementStandards: [],
    componentName: 'PhonicsExplorer',
    patternIds: [11],
  },
  'K-LS-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DebateStructureExplorer',
    patternIds: [13],
  },
  'K-GR-02': {
    status: 'draft',
    prerequisites: ['K-GR-01'],
    achievementStandards: [],
    componentName: 'PhonemeChangeExplorer',
    patternIds: [11],
  },
  'H8-SO-03': {
    status: 'draft',
    prerequisites: ['H8-SO-02'],
    achievementStandards: ['[9사(일사)05-03]'],
    componentName: 'SupplyDemandExplorer',
    patternIds: [1, 14],
  },
  'S3-MA-02': {
    status: 'draft',
    prerequisites: ['S3-MA-01'],
    achievementStandards: ['[4과02-02]'],
    componentName: 'ParticleStateSimulator',
    patternIds: [4],
  },
  'M3-GM-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수03-04]'],
    componentName: 'PolygonAreaExplorer',
    patternIds: [6],
  },
  'S4-LI-01': {
    status: 'draft',
    prerequisites: ['S3-LI-01'],
    achievementStandards: ['[4과05-02]'],
    componentName: 'AnimalHabitatExplorer',
    patternIds: [13],
  },
  'H4-GE-02': {
    status: 'draft',
    prerequisites: ['H4-GE-01'],
    achievementStandards: ['[4사02-03]'],
    componentName: 'KoreaRegionExplorer',
    patternIds: [8],
  },
  'H5-HI-02': {
    status: 'draft',
    prerequisites: ['H5-HI-01'],
    achievementStandards: ['[6사07-03]'],
    componentName: 'KoreanHistoryTimeline',
    patternIds: [7],
  },
  'M3-CR-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수02-01]'],
    componentName: 'SequencePatternDetector',
    patternIds: [14],
  },
  'M4-GM-01': {
    status: 'draft',
    prerequisites: ['M3-GM-01'],
    achievementStandards: ['[4수03-08]'],
    componentName: 'AngleProtractor',
    patternIds: [1, 6],
  },
  'S3-MA-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4과02-01]'],
    componentName: 'ParticleStateSimulator',
    patternIds: [4],
  },
  'M5-NA-06': {
    status: 'draft',
    prerequisites: ['M5-NA-05'],
    achievementStandards: ['[6수01-13]'],
    componentName: 'FractionMultiplicationExplorer',
    patternIds: [12],
  },
  'S3-LI-02': {
    status: 'draft',
    prerequisites: ['S3-LI-01'],
    achievementStandards: ['[4과05-03]'],
    componentName: 'AnimalHabitatExplorer',
    patternIds: [13],
  },
  'M5-GM-02': {
    status: 'draft',
    prerequisites: ['M5-GM-01'],
    achievementStandards: ['[6수03-08]'],
    componentName: 'PolygonAreaExplorer',
    patternIds: [6],
  },
  'H4-HI-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4사04-01]'],
    componentName: 'KoreanHistoryTimeline',
    patternIds: [7],
  },
  'M4-DP-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수04-01]'],
    componentName: 'BarChartBuilder',
    patternIds: [14],
  },
  'H7-GE-02': {
    status: 'draft',
    prerequisites: ['H7-GE-01'],
    achievementStandards: ['[9사(지리)02-01]'],
    componentName: 'WorldContinentExplorer',
    patternIds: [8],
  },
  'H7-GE-03': {
    status: 'draft',
    prerequisites: ['H4-GE-01'],
    achievementStandards: ['[9사(지리)03-01]'],
    componentName: 'KoreaRegionExplorer',
    patternIds: [8],
  },
  'H8-SO-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[9사(일사)01-01]'],
    componentName: 'KoreanModernHistoryTimeline',
    patternIds: [7],
  },
  'S8-LI-01': {
    status: 'draft',
    prerequisites: ['S5-LI-02'],
    achievementStandards: ['[9과10-01]'],
    componentName: 'FoodWebExplorer',
    patternIds: [13],
  },
  'S8-MA-01': {
    status: 'draft',
    prerequisites: ['S7-MA-01'],
    achievementStandards: ['[9과02-03]'],
    componentName: 'ParticleStateSimulator',
    patternIds: [4],
  },
  'E-GR-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'NounArticleExplorer',
    patternIds: [11],
  },
  'E-GR-02': {
    status: 'draft',
    prerequisites: ['E-GR-01'],
    achievementStandards: [],
    componentName: 'PronounCaseMatrix',
    patternIds: [11],
  },
  'K-LT-03': {
    status: 'draft',
    prerequisites: ['K-LT-02'],
    achievementStandards: [],
    componentName: 'CharacterRelationExplorer',
    patternIds: [13],
  },
  'K-LT-04': {
    status: 'draft',
    prerequisites: ['K-LT-02'],
    achievementStandards: [],
    componentName: 'NarratorPerspectiveExplorer',
    patternIds: [13],
  },
  'K-LT-05': {
    status: 'draft',
    prerequisites: ['K-LT-01'],
    achievementStandards: [],
    componentName: 'MetaphorMatchingGame',
    patternIds: [11],
  },
  'K-RD-03': {
    status: 'draft',
    prerequisites: ['K-RD-02'],
    achievementStandards: [],
    componentName: 'InferenceStepsExplorer',
    patternIds: [13],
  },
  'K-WR-01': {
    status: 'draft',
    prerequisites: ['K-RD-01'],
    achievementStandards: [],
    componentName: 'ParagraphStructureBuilder',
    patternIds: [13],
  },
  'K-WR-02': {
    status: 'draft',
    prerequisites: ['K-WR-01'],
    achievementStandards: [],
    componentName: 'OutlinePlannerExplorer',
    patternIds: [13],
  },
  'K-GR-03': {
    status: 'draft',
    prerequisites: ['K-GR-01'],
    achievementStandards: [],
    componentName: 'PartOfSpeechSorter',
    patternIds: [11],
  },
  'K-GR-04': {
    status: 'draft',
    prerequisites: ['K-GR-03'],
    achievementStandards: [],
    componentName: 'SentenceComponentTree',
    patternIds: [13],
  },
  'M5-NA-07': {
    status: 'draft',
    prerequisites: ['M4-NA-01'],
    achievementStandards: ['[6수01-12]'],
    componentName: 'NumberRangeRoundingExplorer',
    patternIds: [12],
  },
  'E-GR-03': {
    status: 'draft',
    prerequisites: ['E-GR-01', 'E-GR-02'],
    achievementStandards: [],
    componentName: 'BeAndDoVerbExplorer',
    patternIds: [11, 12],
  },
  'E-GR-05': {
    status: 'draft',
    prerequisites: ['E-GR-03', 'E-GR-04'],
    achievementStandards: [],
    componentName: 'ModalVerbMatrix',
    patternIds: [11],
  },
  'E-GR-06': {
    status: 'draft',
    prerequisites: ['E-GR-03', 'E-GR-04'],
    achievementStandards: [],
    componentName: 'VerbalFormSimulator',
    patternIds: [12],
  },
  'E-GR-07': {
    status: 'draft',
    prerequisites: ['E-GR-03', 'E-GR-06'],
    achievementStandards: [],
    componentName: 'PassiveVoiceConverter',
    patternIds: [12],
  },
  'E-GR-08': {
    status: 'draft',
    prerequisites: ['E-GR-02', 'E-GR-03'],
    achievementStandards: [],
    componentName: 'RelativeClauseConnector',
    patternIds: [11, 12],
  },
  'E-GR-09': {
    status: 'draft',
    prerequisites: ['E-GR-04', 'E-GR-05'],
    achievementStandards: [],
    componentName: 'ConditionalConverter',
    patternIds: [12],
  },
  'E-GR-10': {
    status: 'draft',
    prerequisites: ['E-GR-01'],
    achievementStandards: [],
    componentName: 'ComparativeSlider',
    patternIds: [1, 12],
  },
  'M6-NA-02': {
    status: 'draft',
    prerequisites: ['M5-NA-04', 'M6-NA-01'],
    achievementStandards: ['[6수01-15]'],
    componentName: 'DecimalDivisionExplorer',
    patternIds: [3, 12],
  },
  'M7-CR-01': {
    status: 'draft',
    prerequisites: ['M6-CR-01'],
    achievementStandards: ['[9수02-01]', '[9수02-02]'],
    componentName: 'AlgebraicExpressionBuilder',
    patternIds: [4, 12],
  },
  'M7-CR-02': {
    status: 'draft',
    prerequisites: ['M7-CR-01'],
    achievementStandards: ['[9수02-03]', '[9수02-04]'],
    componentName: 'LinearEquationBalance',
    patternIds: [3, 14],
  },
  'M7-CR-03': {
    status: 'draft',
    prerequisites: ['M6-CR-01', 'M6-CR-02'],
    achievementStandards: ['[9수02-05]', '[9수02-06]'],
    componentName: 'CoordinatePlaneProportion',
    patternIds: [1, 7],
  },
  'M8-CR-01': {
    status: 'draft',
    prerequisites: ['M7-CR-01'],
    achievementStandards: ['[9수02-07]'],
    componentName: 'ExponentLawExplorer',
    patternIds: [3, 4],
  },
  'M8-NA-01': {
    status: 'draft',
    prerequisites: ['M7-NA-02'],
    achievementStandards: ['[9수01-04]'],
    componentName: 'RepeatingDecimalExplorer',
    patternIds: [3, 12],
  },
  'M9-NA-01': {
    status: 'draft',
    prerequisites: ['M8-NA-01'],
    achievementStandards: ['[9수01-08]', '[9수01-09]'],
    componentName: 'SquareRootNumberLine',
    patternIds: [7, 12],
  },
  'S5-ME-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과11-01]'],
    componentName: 'HeatTransferExplorer',
    patternIds: [4, 17],
  },
  'S5-ME-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과11-02]'],
    componentName: 'TimeDistanceGraph',
    patternIds: [1, 7],
  },
  'S6-ME-01': {
    status: 'draft',
    prerequisites: ['S4-ME-01'],
    achievementStandards: ['[6과09-01]'],
    componentName: 'LensOpticsExplorer',
    patternIds: [1, 17],
  },
  'S6-ME-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6과11-03]'],
    componentName: 'CircuitBuilder',
    patternIds: [4, 17],
  },
  'S6-EU-01': {
    status: 'draft',
    prerequisites: ['S5-EU-01'],
    achievementStandards: ['[6과14-02]'],
    componentName: 'EarthMoonOrbit',
    patternIds: [4, 17],
  },
  'S7-EU-01': {
    status: 'draft',
    prerequisites: ['S6-EU-01'],
    achievementStandards: ['[9과20-01]'],
    componentName: 'RockCyclePlateExplorer',
    patternIds: [13, 17],
  },
  'S7-ME-01': {
    status: 'draft',
    prerequisites: ['S5-ME-02'],
    achievementStandards: ['[9과01-01]'],
    componentName: 'ForceVectorExplorer',
    patternIds: [1, 17],
  },
  'H5-GE-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6사01-01]', '[6사01-02]'],
    componentName: 'KoreaTerritoryExplorer',
    patternIds: [4, 14],
  },
  'H5-GE-02': {
    status: 'draft',
    prerequisites: ['H5-GE-01'],
    achievementStandards: ['[6사01-03]', '[6사01-04]'],
    componentName: 'KoreaEnvironmentLayers',
    patternIds: [4, 14],
  },
  'H5-SO-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6사02-01]', '[6사02-02]'],
    componentName: 'HumanRightsCaseExplorer',
    patternIds: [14, 19],
  },
  'H6-GE-01': {
    status: 'draft',
    prerequisites: ['H5-GE-01'],
    achievementStandards: ['[6사07-01]', '[6사07-02]'],
    componentName: 'WorldContinentExplorer',
    patternIds: [4, 14],
  },
  'H6-SO-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[6사04-01]', '[6사04-02]'],
    componentName: 'SeparationOfPowersExplorer',
    patternIds: [14, 16],
  },
  'H7-SO-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[9사(일사)01-01]', '[9사(일사)01-02]'],
    componentName: 'SocializationStagesExplorer',
    patternIds: [7, 14],
  },
  'H-HI-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[9역01-01]', '[9역01-02]'],
    componentName: 'AncientCivilizationsMap',
    patternIds: [4, 7],
  },
  'H8-GE-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[9사(지리)05-01]'],
    componentName: 'PopulationPyramidExplorer',
    patternIds: [1, 14],
  },
  'M3-DP-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수04-01]'],
    componentName: 'BarChartBuilder',
    patternIds: [14],
  },
  'M3-GM-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수03-12]'],
    componentName: 'ClockExplorer',
    patternIds: [4, 17],
  },
  'M3-GM-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4수03-13]'],
    componentName: 'CapacityWeightExplorer',
    patternIds: [4, 17],
  },
  'S3-EU-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4과16-01]'],
    componentName: 'EarthShapeExplorer',
    patternIds: [4, 17],
  },
  'S3-ME-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[4과08-01]'],
    componentName: 'MagnetExplorer',
    patternIds: [4, 17],
  },
  'M4-DP-02': {
    status: 'draft',
    prerequisites: ['M4-DP-01'],
    achievementStandards: ['[4수04-02]'],
    componentName: 'LineGraphBuilder',
    patternIds: [14],
  },
  'M4-GM-03': {
    status: 'draft',
    prerequisites: ['M3-GM-01'],
    achievementStandards: ['[4수03-09]'],
    componentName: 'TriangleClassifier',
    patternIds: [6],
  },
  'M4-GM-04': {
    status: 'draft',
    prerequisites: ['M3-GM-01'],
    achievementStandards: ['[4수03-10]'],
    componentName: 'QuadrilateralHierarchy',
    patternIds: [6, 13],
  },
  'M7-DP-01': {
    status: 'draft',
    prerequisites: ['M6-DP-01'],
    achievementStandards: ['[9수04-01]'],
    componentName: 'BarChartBuilder',
    patternIds: [10, 14],
  },
  'M7-GM-01': {
    status: 'draft',
    prerequisites: ['M5-GM-01'],
    achievementStandards: ['[9수03-01]'],
    componentName: 'AngleProtractor',
    patternIds: [1, 6],
  },
  'M7-GM-03': {
    status: 'draft',
    prerequisites: ['M7-GM-01'],
    achievementStandards: ['[9수03-04]'],
    componentName: 'PolygonInteriorAngleExplorer',
    patternIds: [1, 6],
  },
  'S7-LI-01': {
    status: 'draft',
    prerequisites: ['S5-LI-01'],
    achievementStandards: ['[9과09-01]'],
    componentName: 'BiologyClassificationTree',
    patternIds: [13],
  },
  'H-HI-02': {
    status: 'draft',
    prerequisites: ['H-HI-01'],
    achievementStandards: ['[9역02-01]'],
    componentName: 'KoreanHistoryTimeline',
    patternIds: [7],
  },
  'H-HI-03': {
    status: 'draft',
    prerequisites: ['H-HI-02'],
    achievementStandards: ['[9역03-01]'],
    componentName: 'KoreanHistoryTimeline',
    patternIds: [7],
  },
  'H7-SO-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: ['[9사(일사)02-01]'],
    componentName: 'SeparationOfPowersExplorer',
    patternIds: [13],
  },
  'M8-CR-02': {
    status: 'draft',
    prerequisites: ['M7-CR-02'],
    achievementStandards: ['[9수02-08]'],
    componentName: 'LinearEquationBalance',
    patternIds: [3, 14],
  },
  'M8-CR-03': {
    status: 'draft',
    prerequisites: ['M8-CR-02'],
    achievementStandards: ['[9수02-09]'],
    componentName: 'SystemOfEquationsExplorer',
    patternIds: [1, 7],
  },
  'M8-CR-04': {
    status: 'draft',
    prerequisites: ['M7-CR-03'],
    achievementStandards: ['[9수02-10]'],
    componentName: 'LinearFunctionExplorer',
    patternIds: [1, 7],
  },
  'M8-CR-05': {
    status: 'draft',
    prerequisites: ['M8-CR-04'],
    achievementStandards: ['[9수02-11]'],
    componentName: 'LinearFunctionExplorer',
    patternIds: [1, 7],
  },
  'M8-GM-01': {
    status: 'draft',
    prerequisites: ['M5-GM-01'],
    achievementStandards: ['[9수03-09]'],
    componentName: 'TriangleClassifier',
    patternIds: [6],
  },
  'M8-GM-03': {
    status: 'draft',
    prerequisites: ['M8-GM-01'],
    achievementStandards: ['[9수03-11]'],
    componentName: 'PythagoreanTheoremExplorer',
    patternIds: [6, 17],
  },
  'S8-MA-02': {
    status: 'draft',
    prerequisites: ['S8-MA-01'],
    achievementStandards: ['[9과02-04]'],
    componentName: 'ParticleStateSimulator',
    patternIds: [4],
  },
  'H8-GE-02': {
    status: 'draft',
    prerequisites: ['H7-GE-03'],
    achievementStandards: ['[9사(지리)06-01]'],
    componentName: 'KoreaRegionExplorer',
    patternIds: [8],
  },
  'M9-CR-01': {
    status: 'draft',
    prerequisites: ['M8-CR-01'],
    achievementStandards: ['[9수02-12]'],
    componentName: 'AreaModelMultiplication',
    patternIds: [12],
  },
  'M9-CR-02': {
    status: 'draft',
    prerequisites: ['M9-CR-01'],
    achievementStandards: ['[9수02-13]'],
    componentName: 'QuadraticFunctionExplorer',
    patternIds: [1, 7],
  },
  'E-E1': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TenseTimelineExplorer',
    patternIds: [7, 12],
  },
  'E-CV': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'BeAndDoVerbExplorer',
    patternIds: [11, 12],
  },
  'E-RW': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'RelativeClauseConnector',
    patternIds: [11, 12],
  },
  'H-EC': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SupplyDemandExplorer',
    patternIds: [1, 14],
  },
  'H-LS': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HumanRightsCaseExplorer',
    patternIds: [14],
  },
  'H-PO': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SeparationOfPowersExplorer',
    patternIds: [13],
  },
  'H-WG': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'WorldContinentExplorer',
    patternIds: [8],
  },
  'E-CE1-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SituationalDialogueSimulator',
    patternIds: [1],
  },
  'E-CE1-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'KeySentenceHighlighter',
    patternIds: [1],
  },
  'E-CE1-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'EnglishWritingBuilder',
    patternIds: [1],
  },
  'E-CE1-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TenseTimelineExplorer',
    patternIds: [1],
  },
  'H-IS1-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MultiPerspectiveAnalyzer',
    patternIds: [1],
  },
  'H-IS1-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HappinessFactorsExplorer',
    patternIds: [1],
  },
  'H-IS1-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ClimateLifestyleSimulator',
    patternIds: [1],
  },
  'H-IS1-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'UrbanizationSimulator',
    patternIds: [1],
  },
  'H-IS1-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HumanRightsCaseExplorer',
    patternIds: [1],
  },
  'H-IS1-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SupplyDemandExplorer',
    patternIds: [1],
  },
  'H-IS2-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'GiniCoefficientExplorer',
    patternIds: [1],
  },
  'H-IS2-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'CultureComparisonMatrix',
    patternIds: [1],
  },
  'H-IS2-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'GlobalizationIndicatorsExplorer',
    patternIds: [1],
  },
  'H-IS2-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SDGsExplorer',
    patternIds: [1],
  },
  'K-CK1-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DebateStructureExplorer',
    patternIds: [1],
  },
  'K-CK1-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TextStructureTree',
    patternIds: [1],
  },
  'K-CK1-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'OutlinePlannerExplorer',
    patternIds: [1],
  },
  'K-CK1-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PhonemeChangeExplorer',
    patternIds: [1],
  },
  'K-CK1-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'LiteraryGenreExplorer',
    patternIds: [1],
  },
  'K-CK1-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MediaComparisonMatrix',
    patternIds: [1],
  },
  'K-CK2-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DebateStructureExplorer',
    patternIds: [1],
  },
  'K-CK2-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'FactOpinionSorter',
    patternIds: [1],
  },
  'K-CK2-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ArgumentStructureBuilder',
    patternIds: [1],
  },
  'K-CK2-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SentenceComponentTree',
    patternIds: [1],
  },
  'K-CK2-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'KoreanLiteraryHistoryTimeline',
    patternIds: [1],
  },
  'K-CK2-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MediaLiteracyExplorer',
    patternIds: [1],
  },
  'M-AL-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ExponentLogExplorer',
    patternIds: [1],
  },
  'M-AL-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ExponentLogFunctionExplorer',
    patternIds: [1],
  },
  'M-AL-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'UnitCircleExplorer',
    patternIds: [1],
  },
  'M-AL-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TrigGraphExplorer',
    patternIds: [1],
  },
  'M-AL-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ArithmeticSequenceExplorer',
    patternIds: [1],
  },
  'M-AL-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'GeometricSequenceExplorer',
    patternIds: [1],
  },
  'M-AL-08': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DominoInductionExplorer',
    patternIds: [1],
  },
  'M-AM-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DataDistributionExplorer',
    patternIds: [1],
  },
  'M-AM-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TfidfVectorExplorer',
    patternIds: [1],
  },
  'M-AM-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ImageFilterExplorer',
    patternIds: [1],
  },
  'M-AM-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MatrixTransformExplorer',
    patternIds: [1],
  },
  'M-AM-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'GradientDescentExplorer',
    patternIds: [1],
  },
  'M-AM-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'NaiveBayesClassifier',
    patternIds: [1],
  },
  'M-CA1-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'FunctionLimitExplorer',
    patternIds: [1],
  },
  'M-CA1-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DerivativeExplorer',
    patternIds: [1],
  },
  'M-CA1-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'RiemannSumExplorer',
    patternIds: [1],
  },
  'M-CA2-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SequenceLimitExplorer',
    patternIds: [1],
  },
  'M-CA2-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MotionDerivativeExplorer',
    patternIds: [1],
  },
  'M-CM1-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PolynomialOperationsExplorer',
    patternIds: [1],
  },
  'M-CM1-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'RemainderTheoremExplorer',
    patternIds: [1],
  },
  'M-CM1-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'AreaModelMultiplication',
    patternIds: [1],
  },
  'M-CM1-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ComplexPlaneExplorer',
    patternIds: [1],
  },
  'M-CM1-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'QuadraticFunctionExplorer',
    patternIds: [1],
  },
  'M-CM1-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'QuadraticFunctionExplorer',
    patternIds: [1],
  },
  'M-CM1-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HigherDegreeEquationExplorer',
    patternIds: [1],
  },
  'M-CM1-08': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PermutationCombinationTree',
    patternIds: [1],
  },
  'M-CM2-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PlaneCoordinateExplorer',
    patternIds: [1],
  },
  'M-CM2-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'LinearFunctionExplorer',
    patternIds: [1],
  },
  'M-CM2-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'CircleEquationExplorer',
    patternIds: [1],
  },
  'M-CM2-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TransformationExplorer',
    patternIds: [1],
  },
  'M-CM2-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'VennDiagramExplorer',
    patternIds: [1],
  },
  'M-CM2-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TruthTableExplorer',
    patternIds: [1],
  },
  'M-CM2-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'FunctionBoxExplorer',
    patternIds: [1],
  },
  'M-CM2-08': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'RationalIrrationalFunctionExplorer',
    patternIds: [1],
  },
  'M-EM-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'CompoundInterestExplorer',
    patternIds: [1],
  },
  'M-EM-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'AnnuityCalculator',
    patternIds: [1],
  },
  'M-EM-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ElasticityExplorer',
    patternIds: [1],
  },
  'M-EM-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MarginalAnalysisExplorer',
    patternIds: [1],
  },
  'M-EM-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'KosisDataExplorer',
    patternIds: [1],
  },
  'M-GE-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ConicSectionExplorer',
    patternIds: [1],
  },
  'M-GE-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'VectorPlaneExplorer',
    patternIds: [1],
  },
  'M-GE-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'VectorDotProductExplorer',
    patternIds: [1],
  },
  'M-PS-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PermutationCombinationExplorer',
    patternIds: [1],
  },
  'M-PS-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PascalTriangleExplorer',
    patternIds: [1],
  },
  'M-PS-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ProbabilityVennExplorer',
    patternIds: [1],
  },
  'M-PS-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'BayesTheoremSimulator',
    patternIds: [1],
  },
  'M-PS-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'DiscreteDistributionExplorer',
    patternIds: [1],
  },
  'M-PS-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'NormalDistributionExplorer',
    patternIds: [1],
  },
  'M-PS-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ConfidenceIntervalSimulator',
    patternIds: [1],
  },
  'S-BIO-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'CharacteristicsOfLifeMatrix',
    patternIds: [1],
  },
  'S-BIO-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HumanMetabolismFlow',
    patternIds: [1],
  },
  'S-BIO-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HumanBodySystems',
    patternIds: [1],
  },
  'S-BIO-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ImmuneResponseSimulator',
    patternIds: [1],
  },
  'S-BIO-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PunnettSquareExplorer',
    patternIds: [1],
  },
  'S-BIO-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'NaturalSelectionSimulator',
    patternIds: [1],
  },
  'S-BIO-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'FoodWebExplorer',
    patternIds: [1],
  },
  'S-CHE-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MoleConverterExplorer',
    patternIds: [1],
  },
  'S-CHE-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PeriodicTableExplorer',
    patternIds: [1],
  },
  'S-CHE-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ChemicalBondExplorer',
    patternIds: [1],
  },
  'S-CHE-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MolecularGeometryExplorer',
    patternIds: [1],
  },
  'S-CHE-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ReactionEnergyDiagram',
    patternIds: [1],
  },
  'S-CHE-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PHIndicator',
    patternIds: [1],
  },
  'S-CHE-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ReactionRateExplorer',
    patternIds: [1],
  },
  'S-EAR-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'RockCyclePlateExplorer',
    patternIds: [1],
  },
  'S-EAR-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'GlobalCirculationExplorer',
    patternIds: [1],
  },
  'S-EAR-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'SolarSystemExplorer',
    patternIds: [1],
  },
  'S-EAR-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'GeologicTimescaleExplorer',
    patternIds: [1],
  },
  'S-EAR-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'EarthquakeWaveSimulator',
    patternIds: [1],
  },
  'S-IS1-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'UnitConversionExplorer',
    patternIds: [1],
  },
  'S-IS1-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PeriodicTableExplorer',
    patternIds: [1],
  },
  'S-IS1-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PhotosynthesisExplorer',
    patternIds: [1],
  },
  'S-IS1-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'PendulumFreefallSimulator',
    patternIds: [1],
  },
  'S-IS2-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ChemicalEquilibriumSimulator',
    patternIds: [1],
  },
  'S-IS2-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'HumanBodySystems',
    patternIds: [1],
  },
  'S-IS2-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'BiologyClassificationTree',
    patternIds: [1],
  },
  'S-IS2-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'CarbonCycleExplorer',
    patternIds: [1],
  },
  'S-PHY-01': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'TimeDistanceGraph',
    patternIds: [1],
  },
  'S-PHY-02': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ForceVectorExplorer',
    patternIds: [1],
  },
  'S-PHY-03': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'EnergyTransformExplorer',
    patternIds: [1],
  },
  'S-PHY-04': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'MomentumCollisionExplorer',
    patternIds: [1],
  },
  'S-PHY-05': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'CircuitBuilder',
    patternIds: [1],
  },
  'S-PHY-06': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'WaveInterferenceExplorer',
    patternIds: [1],
  },
  'S-PHY-07': {
    status: 'draft',
    prerequisites: [],
    achievementStandards: [],
    componentName: 'ModernPhysicsExplorer',
    patternIds: [1],
  },
};
